name: Wuff-Wuff
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  kala:
    runs-on: ubuntu-latest
    steps:
#       - name: My first step
#         uses: docker://node:12
      - run: node -v
      - run: docker ps
      - run: |
          node -v
          pwd
          whoami
          ls -lah
      - run: npm ci | true
      - run: pwd

